### ISSUE TITLE
Open issues in Archived projects

### ISSUE THREAD

**Issue by farviewsoft** [chantra/redmine_whining#6]
I'm not sure if this is by design or not, but it's something that i'm fixing in our implementation:

Issues that are still open in archived projects show up in the list of issues that get mailed to the user.  Which is somewhat confusing to most users because everything in an archived project is inaccessible.

I'm presuming this is a change to the find() method parameters.  I'll post an update here when I have one.

**Comment by chantra** [comment]
Actually, I have never used archive :) so it is not by design.
I checked and it was added in rev 549 of redmine.
A project with a status of 9 would be archived.
http://www.redmine.org/projects/redmine/repository/revisions/549/diff/trunk/app/models/project.rb

Could you try http://github.com/chantra/redmine_whining/tree/ignore_archived to see if this works by any chance.

Tks

**Comment by farviewsoft** [comment]
This looks like it should work fine.

Unfortunately, I'm not really able to test this in our environment.  Our code has deviated quite a bit based on different use cases.

BUT, what I did to make sure the projects returned were active is to change Projects.find() to 'Project.active.find()' and that solved the problem.

I'm hoping to post our fork of your plugin once I get the code into a somewhat less embarrassing state.  :)
